---
AWSTemplateFormatVersion: 2010-09-09
Description: |
  its for ssm automation for prometheus intsallation
Parameters:
  PrometheusInstallUrl:
    Type: String
    Description: The URL of the linux installer for Prometheus
    Default: https://github.com/prometheus/prometheus/releases/download/v2.26.0/prometheus-2.26.0.linux-amd64.tar.gz
  NodeExporterInstallUrl:
    Type: String
    Description: The URL of the linux Node Exporter for Prometheus
    Default: https://github.com/prometheus/node_exporter/releases/download/v1.1.2/node_exporter-1.1.2.linux-amd64.tar.gz
  AMPWorkspaceId:
    Type: String
    Description: The AMP workspace ID where we want to remote write Prometheus data
    Default:  ws-ae461c26-fbfa-42bf-b6a1-13c63c0d5ecc
    MinLength: 10
    AllowedPattern: ^[a-zA-Z0-9-]+$
Resources:
  PrometheusScrapeConfig:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "${AWS::StackName}-ScrapeConfig"
      Type: String
      Value: !Sub |
        scrape_configs:
          - job_name: 'node'
            static_configs:
              - targets: ['localhost:9100']

        remote_write:
          - 
            url: https://aps-workspaces.${AWS::Region}.amazonaws.com/workspaces/${AMPWorkspaceId}/api/v1/remote_write
            queue_config:
                max_samples_per_send: 1000
                max_shards: 200
                capacity: 2500
            sigv4:
                region: ${AWS::Region}
      Tags:
        Name: !Ref "AWS::StackName"
  PrometheusServiceConfig:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "${AWS::StackName}-ServiceConfig"
      Type: String
      Value: |
        [Unit]
        Description=Prometheus
        Wants=network-online.target
        After=network-online.target

        [Service]
        User=prometheus
        Group=prometheus
        Type=simple
        ExecStart=/usr/local/bin/prometheus \
           --config.file /etc/prometheus/prometheus.yml \
            --storage.tsdb.path /var/lib/prometheus/ \
            --web.console.templates=/etc/prometheus/consoles \
            --web.console.libraries=/etc/prometheus/console_libraries

        [Install]
        WantedBy=multi-user.target
      Tags:
        Name: !Ref "AWS::StackName"
  NodeExporterServiceConfig:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "${AWS::StackName}-NodeExporter-ServiceConfig"
      Type: String
      Value: |
        [Unit]
        Description=Node Exporter
        Wants=network-online.target
        After=network-online.target

        [Service]
        User=prometheus
        Group=prometheus
        Type=simple
        ExecStart=/etc/prometheus/node_exporter/node_exporter

        [Install]
        WantedBy=multi-user.target
      Tags:
        Name: !Ref "AWS::StackName"
  PrometheusAutomationDocument:
    Type: AWS::SSM::Document
    Properties:
      Content:
        schemaVersion: "2.2"
        description: Installs and configures Prometheus on Linux instances
        parameters:
          PackageUrl:
            type: String
            description: Prometheus package URL
            default: !Ref "PrometheusInstallUrl"
          NodeExporterPackageUrl:
            type: String
            description: Node Exporter package URL
            default: !Ref "NodeExporterInstallUrl"
          ScrapeConfig:
            type: String
            description: The Prometheus scrape configuration
            default: !Sub "resolve:ssm:${PrometheusScrapeConfig}"
          ServiceConfig:
            type: String
            description: The Prometheus service configuration
            default: !Sub "resolve:ssm:${PrometheusServiceConfig}"
          NodeExporterServiceConfig:
            type: String
            description: The Node Exporter service configuration
            default: !Sub "resolve:ssm:${NodeExporterServiceConfig}"
        mainSteps:
          - action: "aws:runShellScript"
            name: "InstallPrometheus"
            inputs:
              timeoutSeconds: "60"
              runCommand:
                - echo 'Downloading and extracting Prometheus'
                - sudo systemctl stop prometheus >/dev/null 2>&1
                - sudo wget {{ PackageUrl }} >/dev/null 2>&1
                - sudo tar xfz prometheus-*.tar.gz
                - if [ $? != 0 ]; then exit 1; fi
                - sudo mv prometheus-*.linux-amd64 prometheus-files
                - sudo rm prometheus-*.tar.gz
                - echo 'Configuring Prometheus'
                - sudo useradd --no-create-home --shell /bin/fase prometheus | >/dev/null 2>&1
                - sudo mkdir -p /etc/prometheus
                - sudo chown prometheus:prometheus /etc/prometheus
                - sudo cp prometheus-files/prometheus /usr/local/bin/
                - sudo cp prometheus-files/promtool /usr/local/bin/
                - sudo chown prometheus:prometheus /usr/local/bin/prometheus
                - sudo chown prometheus:prometheus /usr/local/bin/promtool
                - sudo cp -r prometheus-files/consoles /etc/prometheus/
                - sudo cp -r prometheus-files/console_libraries/ /etc/prometheus/
                - sudo chown -R prometheus:prometheus /etc/prometheus/consoles/
                - sudo chown -R prometheus:prometheus /etc/prometheus/console_libraries/
                - sudo echo "{{ ScrapeConfig }}" > /etc/prometheus/prometheus.yml
                - sudo chown prometheus:prometheus /etc/prometheus/prometheus.yml
                - sudo echo "{{ ServiceConfig }}" > /etc/systemd/system/prometheus.service
                - echo 'Starting Prometheus service'
                - sudo systemctl daemon-reload
                - sudo systemctl enable prometheus >/dev/null 2>&1
                - sudo systemctl start prometheus
                - sudo rm -rf prometheus-files/
                - echo 'Downloading and configururing Node Exporter'
                - sudo systemctl stop node_exporter >/dev/null 2>&1
                - sudo wget {{ NodeExporterPackageUrl }} >/dev/null 2>&1
                - sudo tar xfz node_exporter-*.tar.gz
                - sudo mv node_exporter-*.linux-amd64 node_exporter
                - sudo rm -rf /etc/prometheus/node_exporter
                - sudo mv node_exporter/ /etc/prometheus/node_exporter/
                - sudo rm node_exporter-*.tar.gz
                - sudo chown -R prometheus:prometheus /etc/prometheus/node_exporter
                - sudo echo "{{ NodeExporterServiceConfig }}" > /etc/systemd/system/node_exporter.service
                - sudo systemctl daemon-reload
                - sudo systemctl enable node_exporter >/dev/null 2>&1
                - sudo systemctl start node_exporter
      DocumentFormat: YAML
      DocumentType: Command
      Name: !Sub "${AWS::StackName}-prometheus-installer"
      Tags:
        - Key: Name
          Value: !Ref "AWS::StackName"
Outputs:
  AutoscalingGroupName:
    Description: The name of the AutoScaling Group that will trigger a Prometheus
      auto-install event
    Value: !Sub 'AutoScale-${AWS::StackName}'
