---
Resources:
  MyDocument:
    Type: AWS::SSM::Document
    Properties:
      Content:
        schemaVersion: "2.2"
        description: "Run a script on Linux instances."
        mainSteps:
          - action: aws:runShellScript
            name: runCommands
            inputs:
              timeoutSeconds: "60"
              runCommand:
                - sudo echo "{{resolve:ssm:ServiceConfig}}" > /etc/systemd/system/prometheus.service
      DocumentFormat: YAML
      DocumentType: Command
      Name: !Sub "${AWS::StackName}"
Outputs:
  EchoCommand:
    Value:  sudo echo "{{resolve:ssm:ServiceConfig}}" > /etc/systemd/system/prometheus.service