---
AWSTemplateFormatVersion: 2010-09-09
Description: |
  its for ssm automation for prometheus intsallation
Parameters:
  AMPWorkspaceId:
    Type: String
    Description: The AMP workspace ID where we want to remote write Prometheus data
    Default:  ws-ae461c26-fbfa-42bf-b6a1-13c63c0d5ecc
    MinLength: 10
    AllowedPattern: ^[a-zA-Z0-9-]+$
Resources:
  PrometheusScrapeConfig:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "PrometheusScrapeConfig"
      Type: String
      Value: !Sub |
        scrape_configs:
          - job_name: 'node'
            static_configs:
             -  targets: ['localhost:9100']
                remote_write:
                  - url: https://aps-workspaces.${AWS::Region}.amazonaws.com/workspaces/${AMPWorkspaceId}/api/v1/remote_write
                    queue_config:
                    max_samples_per_send: 1000
                    max_shards: 200
                    capacity: 2500
                    sigv4:
                      region: ${AWS::Region}
      Tags:
        Name: !Ref "AWS::StackName"
  PrometheusServiceConfig:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "PrometheusServiceConfig"
      Type: String
      Value: |
        [Unit]
        Description=Prometheus
        Wants=network-online.target
        After=network-online.target

        [Service]
        User=prometheus
        Group=prometheus
        Type=simple
        ExecStart=/usr/local/bin/prometheus \
           --config.file /etc/prometheus/prometheus.yml \
            --storage.tsdb.path /var/lib/prometheus/ \
            --web.console.templates=/etc/prometheus/consoles \
            --web.console.libraries=/etc/prometheus/console_libraries

        [Install]
        WantedBy=multi-user.target
      Tags:
        Name: !Ref "AWS::StackName"
  NodeExporterServiceConfig:
    Type: AWS::SSM::Parameter
    Properties:
      Name:  "NodeExporterServiceConfig"
      Type: String
      Value: |
        [Unit]
        Description=Node Exporter
        Wants=network-online.target
        After=network-online.target

        [Service]
        User=prometheus
        Group=prometheus
        Type=simple
        ExecStart=/etc/prometheus/node_exporter/node_exporter

        [Install]
        WantedBy=multi-user.target
      Tags:
        Name: !Ref "AWS::StackName"
Outputs:
  PrometheusScrapeConfig:
    Description: PrometheusScrapeConfig
    Value: !Sub '{{ssm:${PrometheusScrapeConfig}}}'
  PrometheusServiceConfig:
    Description: PrometheusServiceConfig
    Value:  !Sub '{{ssm:${PrometheusServiceConfig}}}'
  PrometheusNodeExporterServiceConfig:
    Description: NodeExporterServiceConfig
    Value:  !Sub '{{ssm:${NodeExporterServiceConfig}}}'
